### ISSUE TITLE
[SoD] HideRaidManager Broken in Latest P5 Patch

### ISSUE THREAD

**Issue by skylight12345** [ketho-wow/HideRaidManager#1]
Hi there, in the latest patch for Season of Discovery this mod finally stopped working and is reporting bugs through BugSack. Any chance of a fix for this would be hugely appreciated as it's one of the most lightweight solutions to hiding this annoying raid manager in Classic.

Thanks in advance for any help/fixes:

191x HideRaidManager/HideRaidManager.lua:17: attempt to call global 'GetMouseFocus' (a nil value)
[string "@HideRaidManager/HideRaidManager.lua"]:17: in function <HideRaidManager/HideRaidManager.lua:16>

Locals:
self = CompactRaidFrameManager {
 displayFrame = CompactRaidFrameManagerDisplayFrame {
 }
 toggleButton = CompactRaidFrameManagerToggleButton {
 }
 container = CompactRaidFrameContainer {
 }
 dynamicContainerPosition = true
 collapsed = true
 containerResizeFrame = CompactRaidFrameManagerContainerResizeFrame {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
manager = CompactRaidFrameManager {
 displayFrame = CompactRaidFrameManagerDisplayFrame {
 }
 toggleButton = CompactRaidFrameManagerToggleButton {
 }
 container = CompactRaidFrameContainer {
 }
 dynamicContainerPosition = true
 collapsed = true
 containerResizeFrame = CompactRaidFrameManagerContainerResizeFrame {
 }
}

**Comment by Ketho** [comment]
Sounds like an easy fix, I'll look when I have time tomorrow

**Comment by skylight12345** [comment]
Thanks Ketho!

**Comment by Ketho** [comment]
I was busy lately sorry, should be fixed in 1.1.0
